---
title: "histograms"
author: "Fabienne Christen"
date: "2/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(jsonlite)
library(ggplot2)
library(dplyr)
library(wordcloud)
```
# text analysis 
```{r}
#read in data
lavaux_categories<-read.csv("data/lavaux_landschaft.csv", sep=";")

lavaux_subset<-lavaux_categories%>%subset(category!='')

#group data and aggregate according to count
lavaux_categories_grouped <- lavaux_categories %>% group_by(category)%>%
  summarise(count = sum(count))%>% na.omit()%>%subset(category!='')

#calculate percentage of each category 
lavaux_categories_grouped$percentage<-lavaux_categories_grouped$count/sum(lavaux_categories_grouped$count)*100

lavaux_categories_grouped$site<-"lavaux"

#read in data
rhb_categories<-read.csv("data/rhb_landschaft.csv", sep=";")

rhb_subset<-rhb_categories%>%subset(category!='')

#group data and aggregate according to count
rhb_categories_grouped <- rhb_categories %>% group_by(category)%>%
  summarise(count = sum(count))%>% na.omit()%>%subset(category!='')

#calculate percentage of each category 
rhb_categories_grouped$percentage<-rhb_categories_grouped$count/sum(rhb_categories_grouped$count)*100

rhb_categories_grouped$site<-"rhb"

#bind data
data_categories<-rhb_categories_grouped%>%
  rbind(lavaux_categories_grouped)
```

```{r}
#plotting data

#png("plots/categories_text.png")
ggplot(data_categories, aes(x=category, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated words [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"), label=c("Lavaux", "RhB"), name="Site")+
  xlab("Landscape properties")
  
#dev.off()
```
#image processing

```{r}
#read in data
lavaux_flickr_categories<-read.csv("data/lavaux_flickr.csv", sep=";")

#group data and aggregate according to count
lavaux_flickr_grouped <- lavaux_flickr_categories %>% group_by(category)%>%
  summarise(count = sum(count))%>% na.omit()%>%subset(category!='')

#calculate percentage of each category 
lavaux_flickr_grouped$percentage<-lavaux_flickr_grouped$count/sum(lavaux_flickr_grouped$count)*100

lavaux_flickr_grouped$site<-"lavaux"


#read in data
rhb_flickr_categories<-read.csv("data/rhb_flickr.csv", sep=";")

#group data and aggregate according to count
rhb_flickr_grouped <- rhb_flickr_categories %>% group_by(category)%>%
  summarise(count = sum(count))%>% na.omit()%>%subset(category!='')

#calculate percentage of each category 
rhb_flickr_grouped$percentage<-rhb_flickr_grouped$count/sum(rhb_flickr_grouped$count)*100

rhb_flickr_grouped$site<-"rhb"



#bind data
flickr_categories<-rhb_flickr_grouped%>%
  rbind(lavaux_flickr_grouped)%>%subset(category!='')


```

```{r}
#plotting data

#png("plots/categories_flickr.png")
ggplot(flickr_categories, aes(x=category, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated tags [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"), label=c("Lavaux", "RhB"), name="Site")+
  xlab("Landscape properties")
#dev.off()
```
# creating wordclouds
```{r}

#png("plots/wordcloud_lavaux_text.png")
wordcloud(words = lavaux_categories$word, freq = lavaux_categories$count, min.freq = 8,max.words=150, random.order=FALSE, rot.per=0.35,ordered.colors = TRUE, colors=brewer.pal(8, "Dark2")[factor(lavaux_categories$category)], scale = c(3.5, 0.25),
          )


#dev.off()
```
```{r}
#png("plots/wordcloud_rhb_text.png")
wordcloud(words = rhb_categories$word, freq = rhb_categories$count, min.freq = 7,max.words=150, random.order=FALSE, rot.per=0.35, ordered.colors = TRUE, colors=brewer.pal(8, "Dark2")[factor(rhb_categories$category)], scale = c(3.5, 0.5))
#dev.off()
```
```{r}
#png("plots/wordcloud_rhb_flickr.png")
wordcloud(words = rhb_flickr_categories$word, freq = rhb_flickr_categories$count, min.freq = 52,max.words=150, random.order=FALSE, rot.per=0.35,ordered.colors = TRUE, colors=brewer.pal(8, "Dark2")[factor(rhb_flickr_categories$category)], scale = c(3.5, 0.5))
#dev.off()
```
```{r}
#png("plots/wordcloud_lavaux_flickr.png")
wordcloud(words = lavaux_flickr_categories$word, freq = lavaux_flickr_categories$count, min.freq = 25,max.words=150, random.order=FALSE, rot.per=0.35,ordered.colors = TRUE, colors=brewer.pal(8, "Dark2")[factor(lavaux_flickr_categories$category)], scale = c(3.5, 0.5))
#dev.off()
```

