---
title: "subceategories"
author: "Fabienne Christen"
date: "7 4 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(jsonlite)
library(ggplot2)
library(dplyr)
library(sqldf)
```
#read in data
```{r}
#read in data
lavaux_flickr_categories<-read.csv("data/lavaux_flickr.csv", sep=";")

#group data and aggregate according to count
lavaux_flickr_subcategories<-sqldf('SELECT category, subcategory, sum(count) count FROM lavaux_flickr_categories GROUP BY subcategory')%>%
  na.omit()%>%subset(subcategory!='')

#calculate percentage of each category 
lavaux_flickr_subcategories$percentage<-lavaux_flickr_subcategories$count/sum(lavaux_flickr_subcategories$count)*100

lavaux_flickr_subcategories$site<-"lavaux"


```



#Visualization of all subcategories of each site
```{r}
#read in data
rhb_flickr_categories<-read.csv("data/rhb_flickr.csv", sep=";")

#group data and aggregate according to count
rhb_flickr_subcategories<- sqldf('SELECT category, subcategory, sum(count) count FROM rhb_flickr_categories GROUP BY subcategory')%>%
  na.omit()%>% na.omit()%>%subset(subcategory!='')

#calculate percentage of each category 
rhb_flickr_subcategories$percentage<-rhb_flickr_subcategories$count/sum(rhb_flickr_subcategories$count)*100

rhb_flickr_subcategories$site<-"rhb"
```

```{r}
ggplot(rhb_flickr_subcategories, aes(x=category, y=percentage, fill = subcategory)) + 
  geom_bar(stat ="identity")
```

```{r}
ggplot(lavaux_flickr_subcategories, aes(x=category, y=percentage, fill = subcategory)) + 
  geom_bar(stat ="identity")
```
#look only at biophysical catgory for each site
```{r}
#look at only biopyhisical category
lavaux_biophysical <- lavaux_flickr_subcategories%>%subset(category=="biophysical")
#calculate percentage of each category 
lavaux_biophysical$percentage<-lavaux_biophysical$count/sum(lavaux_biophysical$count)*100

#look at only biopyhisical category
rhb_biophysical <- rhb_flickr_subcategories%>%subset(category=="biophysical")
#calculate percentage of each category 
rhb_biophysical$percentage<-rhb_biophysical$count/sum(rhb_biophysical$count)*100

#bind data
data_biopyhsical<-rhb_biophysical%>%
  rbind(lavaux_biophysical)
```

visualization
```{r}
#png("plots/biophysical_subcategories_flickr.png")
ggplot(data_biopyhsical, aes(x=subcategory, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated tags [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"),label=c("Lavaux", "RhB"), name="Site")+
  xlab("Subcategories of biophysical property")
#dev.off()
```

#look at cultural category for each site

```{r}
#look at only biopyhisical category
lavaux_cultural <- lavaux_flickr_subcategories%>%subset(category=="cultural")
#calculate percentage of each category 
lavaux_cultural$percentage<-lavaux_cultural$count/sum(lavaux_cultural$count)*100

#look at only biopyhisical category
rhb_cultural <- rhb_flickr_subcategories%>%subset(category=="cultural")
#calculate percentage of each category 
rhb_cultural$percentage<-rhb_cultural$count/sum(rhb_cultural$count)*100

#bind data
data_cultural<-rhb_cultural%>%
  rbind(lavaux_cultural)
```

visualization
```{r}
#png("plots/cultural_subcategories_flickr.png")
ggplot(data_cultural, aes(x=subcategory, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  scale_x_discrete(labels=c("anthropogenic\nobjects", "domesticated\nanimals", "infrastructure", "land use", "settlement"))+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated tags [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"), label=c("Lavaux", "RhB"), name="Site")+
  xlab("Subcategories of cultural property")
#dev.off()
```


# do the same for text data
```{r}
#read in data
lavaux_text_categories<-read.csv("data/lavaux_landschaft.csv", sep=";")

#group data and aggregate according to count
lavaux_text_subcategories<-sqldf('SELECT category, subcategory, sum(count) count FROM lavaux_text_categories GROUP BY subcategory')%>%
  na.omit()%>%subset(subcategory!='')

#calculate percentage of each category 
lavaux_text_subcategories$percentage<-lavaux_text_subcategories$count/sum(lavaux_text_subcategories$count)*100

lavaux_text_subcategories$site<-"lavaux"


```

```{r}
#read in data
rhb_text_categories<-read.csv("data/rhb_landschaft.csv", sep=";")

#group data and aggregate according to count
rhb_text_subcategories<- sqldf('SELECT category, subcategory, sum(count) count FROM rhb_text_categories GROUP BY subcategory')%>%
  na.omit()%>% na.omit()%>%subset(subcategory!='')

#calculate percentage of each category 
rhb_text_subcategories$percentage<-rhb_text_subcategories$count/sum(rhb_text_subcategories$count)*100

rhb_text_subcategories$site<-"rhb"
```

```{r}
ggplot(rhb_text_subcategories, aes(x=category, y=percentage, fill = subcategory)) + 
  geom_bar(stat ="identity")
```

```{r}

ggplot(lavaux_text_subcategories, aes(x=category, y=percentage, fill = subcategory)) + 
  geom_bar(stat ="identity")
```
#look only at biophysical catgory for each site
```{r}
#look at only biopyhisical category
lavaux_text_biophysical <- lavaux_text_subcategories%>%subset(category=="biophysical")
#calculate percentage of each category 
lavaux_text_biophysical$percentage<-lavaux_text_biophysical$count/sum(lavaux_text_biophysical$count)*100

#look at only biopyhisical category
rhb_text_biophysical <- rhb_text_subcategories%>%subset(category=="biophysical")
#calculate percentage of each category 
rhb_text_biophysical$percentage<-rhb_text_biophysical$count/sum(rhb_text_biophysical$count)*100

#bind data
data_text_biopyhsical<-rhb_text_biophysical%>%
  rbind(lavaux_text_biophysical)
```

visualization
```{r}
#png("plots/biophysical_subcategories_text.png")
ggplot(data_text_biopyhsical, aes(x=subcategory, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated words [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"),label=c("Lavaux", "RhB"), name="Site")+
  xlab("Subcategories of biophysical property")
#dev.off()
```

#look at cultural category for each site

```{r}
#look at only biopyhisical category
lavaux_text_cultural <- lavaux_text_subcategories%>%subset(category=="cultural")
#calculate percentage of each category 
lavaux_text_cultural$percentage<-lavaux_text_cultural$count/sum(lavaux_text_cultural$count)*100

#look at only biopyhisical category
rhb_text_cultural <- rhb_text_subcategories%>%subset(category=="cultural")
#calculate percentage of each category 
rhb_text_cultural$percentage<-rhb_text_cultural$count/sum(rhb_text_cultural$count)*100

#bind data
data_text_cultural<-rhb_text_cultural%>%
  rbind(lavaux_text_cultural)
```

visualization
```{r}
#png("plots/cultural_subcategories_text.png")
ggplot(data_text_cultural, aes(x=subcategory, y=percentage, fill=site))+
  geom_bar(stat="identity", position = position_dodge(), width = 0.5)+
  scale_x_discrete(labels=c("anthropogenic\nobjects", "infrastructure", "land use", "settlement", "time depth"))+
  theme_minimal()+
  ylim(0,80)+
  ylab("Annotated words [%]")+
  scale_fill_manual(values=c("#0c5da5", "#ff3100"), label=c("Lavaux", "RhB"), name="Site")+
  xlab("Subcategories of cultural property")
^dev.off()
```


